title: Philip Yoon
logo: "/images/resized_profile.png" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Philip and I'm currently studying Applied Statistics at the University of California, Santa Barbara. My latest project is working on deploying a keras decision tree classifier model as an endpoint using flask. I am always looking to improve my technical skills, so please don't hesitate to give constructive critique. 
  <br><br>
  Other than work, I enjoy movies, rock climbing, and reading self-help and science fiction books. If you'd like to talk or connect about anything please reach out to me! yoonphilip99 (at) gmail (dot) com
  <br><br>
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
