title: Philip Yoon

logo: "/images/resized_profile.png?raw=true" # photo here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome to my rambling regarding technical projects. This summer, I've been learning to
  build and deploy basic web apps using Flask, trying to get an overview of backend web development predicaments. 
  Additionally, I've been working on implementing a dashboard showing some (yet to be determined) interesting statistics on said web app 
  to understand the process of pipelining data to a deployed application. Ultimately, this summer I want to integrate my data and 
  development projects with the goal of learning as much as I can from what will inevitably be a frustrating and rewarding experience. 
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
