title: Philip Yoon

logo: "/images/resized_profile.png?raw=true" # photo here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I'm currently a 4th year at the University of California, Santa Barbara majoring in Statistics and Data Science, although recently I've 
  shifted more towards data engineering and development. I'm currently learning Airflow to practice building basic ETL/ELT systems and learning 
  how to work with relational databases addressing issues like referential integrity or concurrency control.
  <br>
  
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
