title: Philip Yoon

logo: "/images/resized_profile.png?raw=true" # photo here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  My name is Philip and I am studying Applied Statistics at UCSB. My latest project is deploying a keras decision tree classifier model as an endpoint using flask. I am always looking to improve my technical skills, so please don't hesitate to give constructive critique. 
  <br><br>
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
