title: Philip Yoon

logo: "/images/resized_profile.png?raw=true" # photo here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I'm currently a 4th year at the University of California, Santa Barbara majoring in Statistics and Data Science looking for opportunities in analytics regarding business/product performance. My current learning goals are in using Apache Airflow to automate and schedule data pipeline tasks in combination with visualization software like Tableau to create things like KPI dashboards.  
  <br>
  
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
