title: Philip Yoon

logo: "/images/resized_profile.png?raw=true" # photo here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  B.S. in Statistics and Data Science from UCSB.
  Career goals in software development specifically cloud platforms.
  Current learning goals are with Springboot and REST apis.
  <br>
  
  <a href="https://www.linkedin.com/in/mpy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
